### ISSUE TITLE
Update html files during publish if project metadata changed after previous publish

### ISSUE THREAD

**Issue by gideonthomas** [mozilla/publish.webmaker.org#240]
Although https://github.com/mozilla/thimble.mozilla.org/issues/719 has been fixed, it doesn't actually update the published project itself, since on publish, we check from file changes only and only update the files on S3 that have changed since the last publish. We don't check for changes to project metadata and hence, we don't update the remix metadata that is stored in each html file on S3. This results in stale remix metadata being used in the published project.

We should diff the project and publishedProject metadata [here](https://github.com/mozilla/publish.webmaker.org/blob/master/api/classes/publisher.js#L245) to check if there were any changes, and if there were, in [this function](https://github.com/mozilla/publish.webmaker.org/blob/master/api/classes/publisher.js#L287-L330) we should force upload html files.

**Comment by Pomax** [comment]
this might be an interesting bug for a CDOT student - comparing two objects is not super complicated, and a good thing to know how to do because you end up using it a lot in other projects

**Comment by lkisac** [comment]
Hi @gideonthomas, I would like to start working on this bug

**Comment by gideonthomas** [comment]
@lkisac sure thing (just a cautionary warning: this might be a slightly challenging bug)! Give me a little bit of time to figure out exactly what needs to be done here and I can add instructions below.

**Comment by lkisac** [comment]
Hi @gideonthomas   I've been working on this bug.  I have an idea how to compare the objects, but I've been having a hard time debugging the lines of code mentioned above.  When I hit save and publish a project, I don't seem to get the breakpoint hit for the `createOrUpdatePublishedProject()` method on [this](https://github.com/mozilla/thimble.mozilla.org/blob/master/services/publish.webmaker.org/api/classes/publisher.js#L228) line, nor the [call](https://github.com/mozilla/thimble.mozilla.org/blob/master/services/publish.webmaker.org/api/classes/publisher.js#L390) to the method.  

I spent some time setting up my VS Code Chrome Debugger but had some issues with hitting breakpoints due to source mapping issue so I put that aside and am using Chrome DevTools but still breakpoints are not hit.  Since I don't have access to S3, can you recommend an approach to testing this?

**Comment by lkisac** [comment]
Hi @gideonthomas  any updates?

**Comment by gideonthomas** [comment]
@lkisac, for testing this, you shouldn't need S3. The publish server, when run locally publishes to your local filesystem. You will actually need to make a change in a file, and then you'll need to trigger a publish which will then trigger your breakpoint that you've set. You won't be able to use chrome's debugger since it is not client-side code. To debug server-side code, you have two options:
1. Use [node-inspector](https://github.com/node-inspector/node-inspector) coupled with node's built in debugger. This is a bit complicated to use, however, will give you full debugging capabilities just like chrome's dev tools. Note that this is only an option if you're running each part of Thimble separately (not using vagrant) since you would need to run the node-inspector on the publish server.
2. How I usually tend to debug smaller issues - add a [console.trace](https://developer.mozilla.org/en-US/docs/Web/API/Console/trace) at the point you want to debug. This works similar to `console.log` but also gives you a stack trace of the function call (if that is helpful to you). If you see the log in your terminal window running the publish server, that means that your function is being hit.

Regarding the issue itself, to fix it:
- In this `if` statement: https://github.com/mozilla/publish.webmaker.org/blob/master/api/classes/publisher.js#L238, before returning, you would need to compare the properties of `publishedProject` and `project` (mainly `title` and `description`). If they are different, you would need to set a flag on `this` indicating that the html files of the published project need to be updated with the new remix metadata.
- Add another method [to the `publishedFilesQueryBuilder`](https://github.com/mozilla/publish.webmaker.org/blob/master/api/modules/publishedFiles/model.js#L7) called `getAllFilesMatchPath(publishedId, pattern, ignorePaths)` that will run a similar query to: https://github.com/mozilla/publish.webmaker.org/blob/master/api/modules/publishedFiles/model.js#L80-L82 with another `where` tacked on `where(this.context.column('path'), 'like', pattern)`. Also tack on a `whereNotIn` clause (http://knexjs.org/#Builder-whereNotIn) that will be something like `whereNotIn(this.context.column('path'), ignorePaths)`. Make sure your select is the same as: https://github.com/mozilla/publish.webmaker.org/blob/master/api/modules/publishedFiles/model.js#L31-L35.
- Add another `then` function in between https://github.com/mozilla/publish.webmaker.org/blob/master/api/classes/publisher.js#L311-L312 that will take the `publishedFiles` argument as well. In it, return the result of calling the new `publishedFileQueryBuilder` function that you've created above with a `then` tacked on. So, your code will look something like:
```js
.getAllModifiedFiles(this.publishedProject.id)
.then(function(publishedFiles) {
  if(!this.updateHtmlFilesWithNewRemixDataOrWhateverFlagYouUsed) {
    return publishedFiles;
  }

  var ignorePaths;
  if(publishedFiles.length) {
    ignorePaths = publishedFiles.map(publishedFile => publishedFile.oldPath);
  }

  return publishedFilesQueryBuilder
  .getAllFilesMatchPath(this.publishedProject.id, `%.html`, ignorePaths)
  .then(function(publishedHtmlFiles) {
    return publishedFiles.concat(publishedHtmlFiles);
  });
})
.then(function(publishedFiles) ...
```
You will also need to change this condition: https://github.com/mozilla/publish.webmaker.org/blob/master/api/classes/publisher.js#L322 to be `if(!oldPath || oldPath === publishedFile.path)`

I think that's all you need to do to fix this issue. Let me know if you have any clarifications/questions.

**Comment by lkisac** [comment]
@gideonthomas   Thanks for your suggestions and clear explanation.

I've made changes to the necessary files and added a few `console.log` and `console.trace` lines in publisher.js to test it out.  Regarding your suggestions, just to clarify, are both required that I run the publish server only?  In that case, do I need to do each installation step [here](https://github.com/mozilla/publish.webmaker.org)?  

Also, I have Vagrant running my local Thimble instance now - do I need to halt or destroy my current VM and/or end brackets session to run the publish server only?

**Comment by gideonthomas** [comment]
I think you can use vagrant for console.log debugging (I think you'll need to run vagrant halt + vagrant up again so that your console.log changes are reflected). I think after that, you can probably do `vagrant suspend` and `vagrant up` when you make changes to the publish code. Note: this is assuming that you're making changes to the publish code inside the `services/publish.webmaker.org` folder in your thimble folder that you're running vagrant from.

**Comment by lkisac** [comment]
I ran vagrant halt + vagrant up after adding console logs but I don't see any output.  I don't know if that part of the code is not hit, or if it's something else.  Should I be seeing the console log in Chrome DevTools console?  

![thimble_debug3](https://cloud.githubusercontent.com/assets/5377677/23880114/ee46b692-0827-11e7-9187-03b82a2f97e6.gif)

These changes are in the **services/publish.webmaker.org** folder in my thimble folder running vagrant.

**Comment by gideonthomas** [comment]
@lkisac sorry, I think I forgot to mention how you see the logs, my bad. You won't see the logs in Chrome, you'll see them in your terminal. To show them in terminal, run `npm run logs` in the thimble directory.

**Comment by lkisac** [comment]
@gideonthomas  ah, I didn't think so.  I was just setting up node inspector as well, but I think `npm run logs` should suffice for this bug.  Thanks!

**Comment by lkisac** [comment]
@gideonthomas  Changes are almost working.  

I'm just having an issue with `getAllFilesMatchPath` function:

```javascript
  getAllFilesMatchPath(publishedId, pattern, ignorePaths) {
    if (!ignorePaths) {
      ignorePaths="none";
      console.info("ignorePaths empty");
    }
    console.info("FUNCTION - getAllFilesMatchPath" + "\n"
                 + "publishedId " + publishedId + "\n"
                 + "pattern " + pattern + "\n"
                 + "ignorePaths " + ignorePaths + "\n"
                 + "filesTable.column id: " + this.filesTable.column(`id`) + "\n"
                 + "filesTable.column path: " + this.filesTable.column(`path`) + "\n"
                 + "filesTable.column buffer: " + this.filesTable.column(`buffer`) + "\n"
    );
    return new this.PublishedFilesModel()
    .query()
    .where(this.context.column(`published_id`), publishedId)
    .where(this.context.column(`path`), `like`, pattern)
    .whereNotIn(this.context.column(`path`), ignorePaths)
    .select(
      this.filesTable.column(`id`),
      this.filesTable.column(`path`),
      this.filesTable.column(`buffer`)
    );
  }
```

[npm run logs](https://gist.github.com/lkisac/ac467ea8dfaa5dac1dc14d3d45814f8f) output. 

At line 46 - `error: missing FROM-clause entry for table "files"`

I understand this module uses the [knex](http://knexjs.org/) query builder.  The query above looks ok to me, so I have several info logs to check the values in the query.  Since `ignoredPaths` is null during my test, I thought the that may have caused the query to fail but I took that out and still get the same error message which leads me to believe it may be the `select` statement or maybe something missing after it. (if it's ok that `ignoredPaths` is passed into the query as `null`, please let me know so I can remove the null handling condition)

So I also printed the column values (L6 - 8).

npm run logs:
```bash
filesTable.column id: files.id
filesTable.column path: files.path
filesTable.column buffer: files.buffer
```

Is there anything that stands out in the code or the logs provided?

**Comment by lkisac** [comment]
Hi @gideonthomas   Everything looks good now.  I have one last question before I create the pull request.  I created the `updateHtmlFilesWithNewRemixData` flag as a global var for now, but I'd like to have it as a property to go along with `publisehdProject`, `remixData`, etc, to use it in `this` context.  I've looked at all the required classes/models but can't find where these properties belong to - where can I include the new flag property?

Lastly, do you prefer the pull request be opened inside here (publish.webmaker.org), or thimble.mozilla.org, since the issue it relates to was first opened there?

**Comment by gideonthomas** [comment]
@lkisac, I'm not sure I understand where you've used it as the entire use case will fail if it is a global variable. I think it might be easier if I see some code and comment there. Would you be able to open up a PR and I can take a look at it there?

**Comment by lkisac** [comment]
@gideonthomas  opened PR #242

**Comment by gideonthomas** [comment]
thanks! I'll have to take a look at it this weekend.
