### ISSUE TITLE
use id numbers and "classic" route structure 

### ISSUE THREAD

**Issue by ashleygwilliams** [mozilla/publish.webmaker.org#26]
our api routes are going to be consumed by a client, not a person. pretty-urls are a unecessary complexity here IMO. thoughts?

this also keeps us in line with `api.webmaker.org`

**Comment by jbuck** [comment]
What resources would use the id number over the natural key? All of them?

* User -> Username or user id
* Project -> Username and project name or project id
* File -> Username, project name, and file path or file id

What's a "classic" route structure?

I like the idea of using natural keys instead of id numbers... but I must also admit that every other api we've done uses id numbers.

**Comment by cadecairos** [comment]
I'm in favour of the ID based routing, especially considering there's no need for these routes to be human readable.

+1 to keeping it in line with api.wmo

**Comment by ashleygwilliams** [comment]
we've decided on using `id` and the route issues have been updated by @sedge and @gideonthomas. this is based on general API conventions, the fact that this is not user consumed but client consumed, as well as the fact that it will align with api.webmaker.org.

i'm going to close this issue, @jbuck - if you have further questions, ping me and we can chat :)
