### ISSUE TITLE
Finalize publish.wm.o API

### ISSUE THREAD

**Issue by sedge** [mozilla/publish.webmaker.org#3]
# API for thimble to create, replace, update, and delete projects (publish.webmaker.org)

## Schemas
```js
project: 
{
  name: ...,
  username: ...,
  isIndexable: bool,
  files: [
    {...}
  ],
  publishedAt: DateTime
}

file:
{
  type: "content-type",
  path: "/user/project/nested/index.html",
  link: "https://link/to/file.jpg"
}
```

## RESTful API
GET /projects/:username
* List the given users projects
```javascript
{
  projects: [
    ...
  ]
}
```

GET /projects/:username/:projectname
* Retrieve a single project object

```javascript
{
  projects: ...
}
```
POST /projects
* Create a project for the given user and project not including 
```js
{ Project Object }
```

DELETE /projects/:username/:projectname
* Delete a project for the given user and project

PUT /projects/:username/:projectname
* Updates metadata about a project, including publish/unpublish/name

GET /projects/:username/:projectname/files/:filename
* Get the content for the given file

PUT /projects/:username/:projectname/files/:filename
* Create or replace the content for the given file, with the given Content-Type

DELETE /projects/:username/:projectname/files/:filename
* Delete the given file

## Remote procedure call routes
PUT /projects/:username/:projectname/publish
* Publishes a project by copying the saved version to a publicly accessible end-point. If the project is already published, republish with the working copy.

PUT /projects/:username/:projectname/unpublish
* Unpublishes a project

PUT /projects/:username/:projectname/rename
* Renames a project
```js
{
  newName: ...
}
```

PUT /projects/:username/:projectname/files/:filename/rename
* Renames a file
```js
{
  newName: ...
}
```

**Comment by humphd** [comment]
cc @flukeout, @simonwex 

I think the way this imagines storing a project wrt it being saved-only vs. saved-and-published is wrong.  Luke wants to see us use a publish-creates-a-snapshot-copy vs. publish-flips-an-access-pref.  The reason for this is so that a user can publish1, save1, save2, save3, then publish again, and if save1 and save2 broke the code, it won't affect the published content.  In other words, publish needs to take whatever is in the project (all files) and *copy* them to some new place from which they'll be served.  Subsequent saves won't affect the published content at all.

If I'm misreading the above in regard to this, apologies.  If I'm not misreading, we need to update.

**Comment by sedge** [comment]
You're misreading. That single call would copy the working version of the project to the "publish" folder i.e. whatever is served as the published version of that project.

**Comment by simonwex** [comment]
@sedge, the sequence diagram could help to make that clear

@humphd there are a couple RPC calls int he REST mix that are a touch awkward at the moment. -- Namely `publish` and `rename`.

**Comment by humphd** [comment]
Great, thanks for clarifying.  If this is the case, I don't understand what the `public: bool` is on the project.  Does this represent it being 'public' in the gallery vs. being published?

**Comment by sedge** [comment]
@humphd Yup! I'll update to make it clearer. Perhaps `indexable`?

**Comment by humphd** [comment]
`indexable` is less clear than `public` imho.  I think the name matters less than having some docs that help make it clear what this data means.

**Comment by sedge** [comment]
+1

**Comment by humphd** [comment]
`PUT /projects/:username/:projectname/publish`
      * Publishes a project by copying the saved version to a publicly accessible end-point. If the project is already published, republish with the working copy.

I think I'd drop "if the project is already published" since we'll do the exact same thing in all cases, namely, copy the working copy to the public end-point.

**Comment by humphd** [comment]
PUT /projects/:username/:projectname/files/:filename/rename

Renames a project

Should be "Renames a file" I think.

**Comment by humphd** [comment]
So with file renames, is `file.type` based on file contents or filename (extension)?  If I rename `foo.md` to `foo.html` what is `file.type`?  I suspect we're going to need to have type mirror file extension, since type inference is hard to get right.

**Comment by jbuck** [comment]
yeah, I suspect we'll need to guess based on the file extension

**Comment by gideonthomas** [comment]
Two things I noticed:
* For the project schema, I think we should also add a `publish-link` property to indicate the project's publish end-point, to make it easier for thimble to display a public url when the user clicks "Publish"
* For the file schema, as it is above should be fine for the GET file request. However, for the create/replace PUT request, we need a way to provide data in the schema so maybe a property (instead of link) called `data` to hold a base64 encoded buffer should suffice

**Comment by humphd** [comment]
I filed #11 so that it could percolate while this design is finalized, since I know that's something I want to work toward over the summer.  It would be great if we could build a structure that supported it, even if we don't implement it right away.
